version: "3.8"
services:
  db:
    image: mariadb:10.6.7
    volumes:
      - dbvolume:/var/lib/mysql/data
    platform: linux/x86_64
    env_file: development.env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myproject
      - gem_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: development.env
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0
volumes:
  dbvolume:
  gem_data: